### ISSUE TITLE
Foreign text become garbled in UI (Mac)

### ISSUE THREAD

**Issue by zzxiang** [kobolabs/Kobo-Reader#106]
Foreign text become garbled in UI such as table content in the sidebar.

Book contents are displayed normally.

![image](https://user-images.githubusercontent.com/10098144/118382120-1bbbad00-b62d-11eb-9ecb-336663cab912.png)

Kobo version: 4.26.12741
Mac version: macOS Big Sur 11.3.1

But another Macbook with the same Kobo version and Mac version has no such problem.

**Comment by zzxiang** [comment]
I solved the problem by the following steps:

1. Navigate to System Preferences -> Language & Region -> Application
2. Change the language of Kobo reader to English 
3. Restart Kobo reader

Now the Japanese characters are displayed normally.

![スクリーンショット 2021-05-20 23 42 35](https://user-images.githubusercontent.com/10098144/118999236-1069d800-b9c5-11eb-8cc5-29a00250680b.png)

**Comment by gtalusan** [comment]
👍
