### ISSUE TITLE
Kobo as a writing tool

### ISSUE THREAD

**Issue by fabiosirna** [kobolabs/Kobo-Reader#109]
It would be nice to have a feature in Kobo to turn it into a writing tool like https://github.com/olup/kobowriter

**Comment by imgen** [comment]
I second this

**Comment by rahulmundke** [comment]
Agreed, will give it a go to implement this feature

**Comment by Szybet** [comment]
InkBox OS has such option, now ;)
https://github.com/Szybet/niAudio/tree/main/keyboard
