### ISSUE TITLE
Can't login to my local library

### ISSUE THREAD

**Issue by peheje** [kobolabs/Kobo-Reader#123]
Hi,

Recently bought a Libra 2, I'm trying to login to my local library which does support OverDrive, this used to work on my older device (Kobo Clara), but since then my local library decided to "modernise" the login-page, making it heavily rely on JavaScript to work properly:

https://login.bib.dk/login

Unfortunately the Libra 2 just can't process it and I'm unable to select my library from the list or search for it. So I'm stuck. I'm looking for ways to circumvent this. Is there some way I can login using my PC and sync it/manually move it? I tried logging into my Overdrive account on my PC and connecting the library from here, but that doesn't prompt for login.

I did call in about the issue, but got the answer that "we don't support e-readers". I'm pretty convinced though that this is just a limitation of the compatability of the UI.

This is the info I could find on the library I'm trying to login to.
```
{
      "id": 89643,
      "name": "Aarhus Kommunes Biblioteker",
      "address": "Møllegade 1",
      "city": "Aarhus C",
      "regionCode": "DK",
      "region": "Denmark",
      "postalCode": "8000",
      "countryCode": "DK",
      "country": "Denmark",
      "latitude": 56.1566,
      "longitude": 10.200246,
      "links": [],
      "isMemberInstantAccessSystem": false,
      "systemIds": [
        6247
      ],
      "relevance": 1
    }
```

Through https://libraryfinder.api.overdrive.com/swagger/index.html

**Comment by C0DK** [comment]
Hej 🇩🇰

I raised this issue with their support and they were very difficult to talk with. Wanted me to add a credit card to the store etc, and wouldn't accept a simple bug report. After a very long time they finally accepted my very thorough steps to reproduce and confirmed it. They updated their documentation (a bit half assed imo) and said they would relay it to the development team, but I havent had any updates for many months and when I pinged them I got pretty bad support messages back but with no real update.

It made me regret buying a Kobo product, as they seem to probably underpay staff and have a subpar software team behind the products. Not sure what we can do sadly.

They might fix it, but my best bet had been to contact bib.dk, and ask them to use another site version based on browser agent, however I have not gotten around to it.

**Comment by peheje** [comment]
So about a week ago I tried this out again, this time I was presented with a QR code on the Kobo (when logging into Overdrive with my library card). I needed to scan the QR code with my phone, login there and tada, I was logged in.

I have now read a few rented books. Hurray!

Maybe your persistence helped in the end C0DK? In any case, thanks for your comment here and possibly help.
