### ISSUE TITLE
Request for the Elipsa 2E kernel sources

### ISSUE THREAD

**Issue by NiLuJe** [kobolabs/Kobo-Reader#126]
It's that time of the year again ;).

Hoping the condor will have a smooth flight, cheers!

**Comment by Knut0730** [comment]
Maybe @ringerc can help?

**Comment by Knut0730** [comment]
Or @gtalusan?

**Comment by Gimsu** [comment]
I bought a Kobo Elipsa 2e yesterday and was putting my notes together in preparation to install KOReader then I came across this issue. Would love for this to be fixed so I can use it soon!

**Comment by Szybet** [comment]
Asking via email / messenger support helped to get the clara 2E sources, so you can try that

**Comment by Knut0730** [comment]
> Asking via email / messenger support helped to get the clara 2E sources, so you can try that

Whats the email?

**Comment by Szybet** [comment]
no idea i used messenger

**Comment by Gimsu** [comment]
Thanks for the tip, I don't have Messenger so used Twitter. Here's the link to the options, no email that I can see:

https://help.kobo.com/hc/en-us/requests/new

**Comment by Knut0730** [comment]
> Thanks for the tip, I don't have Messenger so used Twitter. Here's the link to the options, no email that I can see:
> 
> 
> 
> https://help.kobo.com/hc/en-us/requests/new

I have messaged them on Messenger now and awaiting a higher department. 

But as a person unknown to most of the developer universe; what am I actually asking for? A code? A file? 

And if I manage to get these sources, where do I send them so that KOReader can gain support for the Elipsa 2E?

**Comment by Gimsu** [comment]
After speaking with two people via Twitter, I was directed to the Feedback button on the main site kobo.com so I'm filling that out now.

I'm not sure how this worked out in the past, but I hope this results in it getting worked out. I'm kind of stuck as I foolishly didn't search the issues before buying the Elipsa 2e.

**Comment by Szybet** [comment]
As you are on the chat with them, you can ask about other kernel sources ( Clara 2E, Kobo nia ) they are propably outdated

**Comment by Gimsu** [comment]
That chat is closed since they directed me to the Feedback section, there was no response on 1) sources and this issue or 2) if I could downgrade to a firmware which works.

**Comment by NiLuJe** [comment]
> 2) if I could downgrade to a firmware which works.

That makes no sense, first, it's a brand new device, so it's note like there are that many earlier firmwares to pick from to begin with. But, most importantly, the issue isn't the software per se, it's the hardware: it's quite simply a different SoC.

**Comment by Gimsu** [comment]
I apologise for making that mistake, I wasn't aware it was a brand new device. I was just trying to help by contacting them in the hopes that they would attend to this issue.

**Comment by Knut0730** [comment]
Update: I have now gotten in contact with Kobo and they say that they will be uploading the files online, yet there is no ETA for this. When asked if they have any approximate ETA at all I got a blank _no_. I messaged them on Messenger. Was relatively efficient.

**Comment by NiLuJe** [comment]
Resolved via e41d108, thanks!
