### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by lightonflux** [kobolabs/Kobo-Reader#25]
Hi, it is very hard to find the license of Kobo-Reader. I [searched](https://github.com/kobolabs/Kobo-Reader/search?q=license&source=cc) and found that some patches are under some OSI license (well dual licensed).

It would be great if you could add a LICENSE file to the repo, so it is easier to overview the license situation for Kobo-Reader.

**Comment by lightonflux** [comment]
Can we have an explanation why this issue is closed?

**Comment by gtalusan** [comment]
It seems irrelevant.  The patches to the open source project would fall under the license for that project.  This repository is to facilitate the distribution of those projects.  If you want to modify the code, then be my guest.
