### ISSUE TITLE
 Web browser forgetting authentication on Google

### ISSUE THREAD

**Issue by dClauzel** [kobolabs/Kobo-Reader#28]
I am using the web browser for a few limited things, like checking my private messages on Twitter, and my email.

The authentication on Twitter works fine: the cookie keeps me connected between uses.

But Google doesn't trust me when I come back: I am disconnected from gmail. The login form is pre-filed with my login, so there is at least one cookie that is ok, but I would prefer to still being connected : typing a 30+ chars password is annoying as Hell.

I am not sure where the problem is. My Google account works as expected on my computers, but not on the Aura HD.

My Google account is a "Google for business" one, with custom domain name.

**Comment by dClauzel** [comment]
So… ?

**Comment by gtalusan** [comment]
Beyond the purpose of these repositories.
