### ISSUE TITLE
Network error on Kobo Desktop

### ISSUE THREAD

**Issue by mwilliams72** [kobolabs/Kobo-Reader#49]
Yesterday morning it was working fine.  Now when I try to log in to Kobo Desktop I am getting a "Network Error message" and saying my internet connection is not there.  Clearly that is not the case.  What is going on?  How can I get access to Kobo Desktop again?

**Comment by emeryl1** [comment]
Can't get ebook to charge on computer or other usb port.

**Comment by fuzzy76** [comment]
I'm seeing this as well. Cannot sign on on Kobo Desktop.

**Comment by richardh9935** [comment]
I'm getting this error, using 4.2.4917 on MacOS Sierra  10.12.3
@mwilliams72, Did you ever resolve this?

**Comment by fuzzy76** [comment]
Re-installing my computer helped. :( I guess there are some settings / cache files somewhere that doesn't get removed when you remove the app. So you'd probably need a quite detailed uninstall script.

**Comment by fuzzy76** [comment]
But if you have this problem now, you should probably open a new issue since this one has been closed.
