### ISSUE TITLE
Possible (A)GPL violation

### ISSUE THREAD

**Issue by rrooij** [kobolabs/Kobo-Reader#57]
MuPDF seems to be used for rendering PDF's, since it is seen as repository in the kobolabs GitHub account. However, I couldn't find the ereader software itself anywhere. If it incorporates Mupdf, then it must be released under a free software license too, since MuPDF is AGPLv3 licensed.

**Comment by gtalusan** [comment]
It's not used to render PDFs.

**Comment by rrooij** [comment]
Clear, sorry for the misunderstanding.
