### ISSUE TITLE
Opening book crashes the reader

### ISSUE THREAD

**Issue by Reinis** [kobolabs/Kobo-Reader#58]
I have Kobo Glo HD e-reader and I can't open some of the books from Kobo store (reader crashes, restarts).

The problematic books are "My Love 太っちょ" series by Heejung Lee. I checked the first two books in the series and they both had the issue. They are free books so anyone can easily check.

**Comment by gtalusan** [comment]
Thanks, looking into it.

**Comment by Reinis** [comment]
I guess there was an update, it is working now. Thanks.

**Comment by ben-en** [comment]
You can close the issue if it is now working, @Reinis.
