### ISSUE TITLE
Book added to library but never downloaded

### ISSUE THREAD

**Issue by Reinis** [kobolabs/Kobo-Reader#60]
I have a Kobo Glo HD e-reader. Searching in the storefront for "game go" and selecting the free book "The game of go, the national game of Japan" by Arthur Smith and then selecting Download adds the book to the library but it is never downloaded. Selecting the book in the library changes its status from Download to Pending, the screen flashes it says that the Sync Complete and the book's status returns to "Download". So it is actually not possible to read the book even though it is listed as a free book.

**Comment by JOQuantaman** [comment]
I've got PAID-FOR books by Keith Roberts that do NOT show up in my Library.  Kobo is a f--cking Indian Giver.

**Comment by Reinis** [comment]
Working now. Hadn't checked for a long time, but after the recent updates it works.
