### ISSUE TITLE
where can i find the Kobo Aura H2O 2nd edition  GPL source code

### ISSUE THREAD

**Issue by tvo2011** [kobolabs/Kobo-Reader#63]
couldn't find it, the model already release for few monthes, but no source code yet !!

**Comment by gtalusan** [comment]
Woops, it'll come up shortly.

**Comment by gtalusan** [comment]
Here are the kernel and bootloader.

https://github.com/kobolabs/Kobo-Reader/tree/master/hw/imx6sl-aurah2o
