### ISSUE TITLE
Running a script after device unplugged and importing finished.

### ISSUE THREAD

**Issue by geek1011** [kobolabs/Kobo-Reader#66]
I am currently working on a mod for the Kobo to load series metadata for sideloaded books. I have already hacked together a [standalone tool](https://raw.githubusercontent.com/geek1011/kepubify/master/seriesmeta/seriesmeta.go) for this which runs from a computer without any issues.

I have not had any trouble getting it to compile for the Kobo, and have managed to run it without issues over SSH.

Currently, I override the script which handles the usb plug and triggers the importing, but I cannot find any proper way of detecting whether importing is finished so I can update the database.

I would like to know if there is any proper way to detect when the importing process has finished.

**Comment by gtalusan** [comment]
Howdy, there really isn't a good way since this behaviour is internal to the application only.  You could probably listen to ioctls going to the framebuffer using an interposing library similar to the inverted screen plugin and do some pixel snooping.

Good luck.

**Comment by geek1011** [comment]
@gtalusan ok, thanks. That seems like it will work if I can get it to work well with golang. If not, I'll make a helper in C. 

If I have too many issues with this, I may try to patch nickel to write to a file when finished indexing. I already have reassembled nickel a few times for other purposes (but it is VERY time consuming and error-prone).

**Comment by geek1011** [comment]
@gtalusan another quick question: is plugin example in this repo still supposed to work?

**Comment by gtalusan** [comment]
Unfortunately no, it hasn't worked for quite some time.

**Comment by geek1011** [comment]
@gtalusan ok, thanks for the clarification. I'm looking into your fork of the night mode plugin to see what I can do.
