### ISSUE TITLE
Erratic behaviour when reading a particular mobi book

### ISSUE THREAD

**Issue by jonatanhal** [kobolabs/Kobo-Reader#67]
Hello!

While attempting to read the mobi version of [linux insides](https://www.gitbook.com/book/0xax/linux-insides/details), my Kobo aura 6 became unresponsive in the first few pages, and after a minute or two had passed, it seemed that the device crashed and rebooted itself. Upon my second attempt to read the aforementioned book, the same issue manifested itself, and I performed a hard reset by holding the button located on the back of the device for a couple of seconds.

Third time however, it seems that reading the aforementioned book is no longer crashing the device. 

While it is working now, maybe this particular book can be a source of confusion for any Kobo-Reader parsers attempting to make sense of the mobi format. 

Steps to (hopefully) reproduce:

1. download the mobi format of the book, located here: https://www.gitbook.com/book/0xax/linux-insides/details.
2. Transfer the book to the device (in my case I used usb)
3. open the book on the device, attempt to change pages (the device or program should display erratic (not responding to input, or, going back a page while input instructed the device to go forward) behaviour and/or crash at this point)

**Comment by shxdow** [comment]
@jonatanhal Can you post some information about the device you're using (firmware version etc.) ?

**Comment by gtalusan** [comment]
Howdy, this book is enormous.  There's about 450MB of allocations when loading it up.  The reboots that you're getting when paging through the book are likely due to either memory exhaustion and/or fragmentation.

You might have better luck using an EPUB or PDF version, provided the EPUB splits the chapters canonically into separate files.  This would keep memory pressure on the system far lower.

**Comment by jonatanhal** [comment]
@shxdow sure thing, here goes:

serial number: n236710360409
software version: 4.1.7729 (8bedc76ce7, 10/10/16)

@gtalusan that makes sense, thanks for the explanation!
