### ISSUE TITLE
Kepub with large content file causes kobo to reboot

### ISSUE THREAD

**Issue by geek1011** [kobolabs/Kobo-Reader#68]
Kepub files (both converted properly with kepubify, and just renamed) with large (3.5 MB) content files crashes the kepub renderer and causes a reboot. This problem does not occur if the content file is split into smaller parts.

The epub and the converted kepub are completely valid according to ePubCheck. It also renders fine in Adobe Digital Editions, the Calibre reader, and basically any desktop epub reader.

See geek1011/kepubify#15 for the book and more info.

**Comment by geek1011** [comment]
Also, I am reporting this as a bug because this epub fits the limitations (10 MB per content file) in [the kobo epub spec)https://github.com/kobolabs/epub-spec#limitations-and-maximums).

**Comment by gtalusan** [comment]
Hmmm.. should be fixed in the next release.

**Comment by gtalusan** [comment]
BTW, thanks!  Two bugs squashed here.. index out of array bounds and an OOM.

**Comment by geek1011** [comment]
@gtalusan ok, thanks a lot! 

Do you know anything about the recent reading life stats issues (in the latest version, it does not count at all)? It seems to break differently in each release, but works every few releases :smile:.

**Comment by gtalusan** [comment]
Sounds like a separate unrelated issue..... which is also fixed for the next release

**Comment by geek1011** [comment]
OK, great!

**Comment by geek1011** [comment]
Sorry if I'm being a bit pushy, but any ETA for the next release (it seems to be taking longer than usual)? 

I'm itching for some of these bugfixes, and I want to test my release notifications :). It's also fun to play with new FW versions.
