### ISSUE TITLE
Kobo Clara HD

### ISSUE THREAD

**Issue by woachk** [kobolabs/Kobo-Reader#79]
Which hw combination should I use for building a kernel for ClaraHD?

Thanks,

**Comment by gtalusan** [comment]
Coming shortly.

**Comment by woachk** [comment]
@gtalusan thanks! is a set of WiFi modules needed too, or the existing ones work? :)

**Comment by gtalusan** [comment]
They were uploaded previously here: https://github.com/kobolabs/Kobo-Reader/blob/master/hw/imx6sll-aurah2o2-aura/wifi.tgz

**Comment by woachk** [comment]
Thanks, will just need to get everything in order with the right .config now, with kexec set up well enough because I don't want to open the device.

**Comment by yegortimoshenko** [comment]
@gtalusan Which `defconfig` do Clara devices use? I see `imx_v7_kobo_defconfig`, but Clara is i.MX6SLL, not a i.MX7 device. Thanks!

**Comment by gtalusan** [comment]
Sorry for the late reply, @yegortimoshenko.  imx_v7_kobo_defconfig is the right one.

**Comment by brunotl** [comment]
Hi, Which toolchain is needed for compile Clara kernel ?
