### ISSUE TITLE
can not run self build kernel on kobo glo hd

### ISSUE THREAD

**Issue by apreiml** [kobolabs/Kobo-Reader#94]
I've tried to build the kernel from [this repository](https://github.com/kobolabs/Kobo-Reader/tree/master/hw/imx6sl-glohd)

I cross compiled it using gcc4 on armv7. Building it works fine after applying this [patch](https://gist.github.com/apreiml/0745d7d5cfd47f6e485bf08536d6bd74). But it fails during boot with "Unable to handle kernel paging request at virtual address 001c4a60". 

[kernel-fail.log](https://github.com/kobolabs/Kobo-Reader/files/4046146/kernel-fail.log)

I've also tried the device config from /proc/config.gz

**Comment by tux-linux** [comment]
You probably don't need this anymore, but you need to build it with a (slightly) newer toolchain. Grab `arm-nickel-linux-gnueabihf` from here: https://github.com/Kobo-InkBox/kernel/tree/master/toolchain/arm-nickel-linux-gnueabihf
Upstream: https://github.com/pgaskin/NickelTC

**Comment by apreiml** [comment]
Thanks! Maybe I'll dig out the e-reader again :).

**Comment by tux-linux** [comment]
There is an open-source OS I made that supports it now, FWIW: https://inkbox.ddns.net
You can download an SD card image here: http://23.163.0.39/bundles/inkbox/native/n437/inkbox-1.9-n437.xz

**Comment by apreiml** [comment]
neat! I'll definitely check this one out.
